### ISSUE TITLE
Custom IDE key

### ISSUE THREAD

**Issue by bboure** [trizz/insomnia-plugin-xdebug-switch#2]
@trizz  Useful plugin!! Thanks! 
Any plan on allowing a custom ide key?

**Comment by trizz** [comment]
I'm certainly planning to implement some sort of settings, but at this point I don't exactly know how and where to add this. In the meantime, you can update the IDE key by going to `Preferences -> Plugins -> Show Folder` and edit the file [`src/xdebug.js` at line 11](https://github.com/trizz/insomnia-plugin-xdebug-switch/blob/master/src/xdebug.js#L11).

However, in my experience the IDE key is hardly used and is only relevant when you're using a DBGp Proxy. I'm using PhpStorm with `PHPSTORM` as configured key, however, every Xdebug call made by my plugin is also accepted (even with the `INSMONIA` IDE Key).

**Comment by trizz** [comment]
@bboure I've just published version 0.2.0, which allows you to set a custom IDE key by defining it in your sub- or base environment.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/832056/48021137-216cd980-e138-11e8-8a2f-6905377f331a.png">
